# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-01 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_imdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=100)),
                ('rank', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('title', 'person', 'created_at'),
                'verbose_name': 'Credit',
                'verbose_name_plural': 'Credit',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rank', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', related_query_name='role', to='core.Credit')),
            ],
            options={
                'ordering': ('credit', 'name', 'created_at'),
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.RemoveField(
            model_name='titleperson',
            name='person',
        ),
        migrations.RemoveField(
            model_name='titleperson',
            name='title',
        ),
        migrations.AddField(
            model_name='genre',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plot',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trailer',
            name='format',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trailer',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trailorimageurl',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plot',
            name='name',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='title',
            name='certification',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='cover_url',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='plot_outline',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='poster_url',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='runtime',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='tagline',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='votes',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='name',
            field=models.TextField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='TitlePerson',
        ),
        migrations.AddField(
            model_name='credit',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', related_query_name='work', to='core.Person'),
        ),
        migrations.AddField(
            model_name='credit',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casts', related_query_name='cast', to='core.Title'),
        ),
        migrations.AlterUniqueTogether(
            name='credit',
            unique_together=set([('title', 'person')]),
        ),
    ]
