# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-01 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170901_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='release_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
