# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-01 02:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170901_0137'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='credit',
            unique_together=set([]),
        ),
    ]
